name: "Threat Model"

on:
  issues:
    types: [opened, edited, closed, reopened, labeled]
  pull_request:
    types: [opened, edited, closed, reopened, labeled]
  issue_comment:
    types: [created, edited, deleted]

jobs:
  threatModel:
    runs-on: ubuntu-latest
    name: Threat Model Workflow Runner
    steps:
      - name: Invoke The Threat Model Action
        id: threatModelAction
        # github path/repo@<version or branch>
        uses: richardpickett/github-action@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      # - name: Get the output time
      #   run: echo "The time was ${{ steps.threatModelAction.outputs.time }}"
